### ISSUE TITLE
[TRACKER] Complete Project

### ISSUE THREAD

**Issue by JamesHinshelwood** [LimaInc/SustainableCraft#7]
NEW: https://github.com/LimaInc/SustainableCraft/projects/1

Making an issue to keep track of needed features. (Might move this to projects, will investigate)

Sam
- [ ] Planet fauna
- [ ] Population dynamics

David
- [x] #8: Player controller
- [ ] UI
- [ ] Inventory
- [ ] Needs bars

Adam
- [ ] Defossilizer
- [ ] Fossil items
- [x] Bacteria
- [x] Bacteria vials + throwing
- [x] Atmosphere mechanics

James
- [x]  Infinite, procedural world
- [ ] #1: Threading for chunk generation
- [ ] Fossil generation
- [ ] Starting ship generation

Ian
- [ ] Planet flora
- [ ] Plant items
- [ ] Plants spread across planet

Joe
- [ ] Natural distaster

**Comment by JamesHinshelwood** [comment]
Closes #5

**Comment by JamesHinshelwood** [comment]
Moved to project
